id: P000602
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W23154
  title: དཔལ་ལྡན་བླ་མ་ཐམས་ཅད་མཁྱེན་གཟིགས་ཆེན་པོ་ངག་དབང་འཇིགས་མེད་གྲགས་པའི་རྣམ་པར་ཐར་པ་བྱང་ཆེན་སྤྱོད་པའི་རྒྱ་མཚོར་འཇུག་པའི་གཏམ་སྙན་པའི་ཡན་ལག་འབུམ་ལྡན་རྫོགས་ལྡན་དགའ་ཆར་སྦྱིན་པའི་ཆོས་ཀྱི་སྤྲིན་ཆེན་པོའི་དབྱངས
  author: ''
  volumes:
    dd1e528727164e4d8fe903015fe04dba:
      image_group_id: I1675
      title: ''
      volume_number: 1
      total_pages: 739
      base_file: v001.txt
