id: IC7BF428B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T22:01:13+00:00'
last_modified: '2022-06-07T12:25:42.714106+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23154
  title: དཔལ་ལྡན་བླ་མ་ཐམས་ཅད་མཁྱེན་གཟིགས་ཆེན་པོ་ངག་དབང་འཇིགས་མེད་གྲགས་པའི་རྣམ་པར་ཐར་པ་བྱང་ཆེན་སྤྱོད་པའི་རྒྱ་མཚོར་འཇུག་པའི་གཏམ་སྙན་པའི་ཡན་ལག་འབུམ་ལྡན་རྫོགས་ལྡན་དགའ་ཆར་སྦྱིན་པའི་ཆོས་ཀྱི་སྤྲིན་ཆེན་པོའི་དབྱངས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '4489':
      image_group_id: I1675
      title: ''
      total_pages: 739
      order: 1
      base_file: 4489.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
